packages:
  - apps/*
  - packages/*

enablePrePostScripts: true

catalog:
  typescript: ^5.9.3
  zod: ^4.1.13
  prettier: ^3.4.2

catalogs:
  react:
    react: ^19.2.1
    react-dom: ^19.2.1
    "@types/react": ^19.2.7
    "@types/react-dom": ^19.2.3
  next:
    next: 16.0.10
