packages:
  - apps/*
  - packages/*

catalog:
  eslint: ^9.39.1
  prettier: 3.7.4
  typescript: ^5.9.3
  zod: ^4.1.13

catalogs:
  next:
    next: 16.0.10
  react:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: ^19.2.1
    react-dom: ^19.2.1

enablePrePostScripts: true
